# Generated by Django 3.2.7 on 2021-10-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20211005_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='teacher_points',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, verbose_name='teacher_points'),
        ),
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='text'),
        ),
    ]
