# Generated by Django 3.2.7 on 2021-10-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20211028_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.IntegerField(blank=True, default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='teacher_points',
            field=models.IntegerField(blank=True, default=0, verbose_name='teacher_points'),
        ),
    ]
