# Generated by Django 3.2.7 on 2021-10-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20211028_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='points',
        ),
    ]
