# Generated by Django 3.2.7 on 2021-10-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_answer_points'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('-id',)},
        ),
    ]
