# Generated by Django 3.2.7 on 2021-11-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20211103_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='valid',
            field=models.BooleanField(default=False, verbose_name='valid'),
        ),
    ]
