# Generated by Django 3.2.7 on 2021-10-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20211007_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='sub_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='sub_semester',
            new_name='semester',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='sub_year',
            new_name='year',
        ),
    ]
