# Generated by Django 3.2.7 on 2021-10-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_auto_20211010_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
