# Generated by Django 3.2.7 on 2021-10-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_alter_subject_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
