# Generated by Django 3.2.7 on 2021-10-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_merge_0008_auto_20211013_1406_0008_auto_20211013_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
