# Generated by Django 3.2.7 on 2021-10-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0010_subject_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.IntegerField(null=True, verbose_name='Ročník'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('zimní', 'Winter'), ('letní', 'Summer')], max_length=20, null=True, verbose_name='Semestr'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='shortcut',
            field=models.CharField(max_length=6, null=True, verbose_name='Zkratka předmětu'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Rok'),
        ),
    ]
