# Generated by Django 3.2.7 on 2021-10-19 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0013_alter_subject_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='category_name'),
        ),
        migrations.AddField(
            model_name='category',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
