# Generated by Django 3.2.7 on 2021-10-19 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_auto_20211019_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
