# Generated by Django 3.2.7 on 2021-10-19 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0015_alter_category_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
    ]
