# Generated by Django 3.2.7 on 2021-10-20 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0014_auto_20211019_1441'),
        ('subjects', '0014_auto_20211019_1448'),
        ('subjects', '0016_alter_category_subject'),
    ]

    operations = [
    ]
