# Generated by Django 3.2.7 on 2021-10-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0017_merge_20211020_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='confirmed',
            field=models.BooleanField(default=False, null=True, verbose_name='Schválit předmět'),
        ),
    ]
