# Generated by Django 3.2.7 on 2021-10-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0018_alter_subject_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='confirmed',
            field=models.BooleanField(choices=[('schválit', 'Confirm'), ('zamítnout', 'Reject')], default=False, null=True, verbose_name='Schválit předmět'),
        ),
    ]
