# Generated by Django 3.2.7 on 2021-11-03 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0021_auto_20211103_2044'),
        ('accounts', '0002_karma_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karma',
            name='karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='karma',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
