# Generated by Django 3.2.7 on 2021-10-04 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211003_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
    ]
