# Generated by Django 3.2.7 on 2021-11-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='compulsory',
            field=models.CharField(choices=[('compulsory', 'Povinný'), ('uncompulsory', 'Nepovinný')], default='uncompulsory', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('winter', 'Zimní'), ('summer', 'Letní')], default='winter', max_length=20),
        ),
    ]
