# Generated by Django 3.2.7 on 2021-11-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20211112_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
