# Generated by Django 3.2.7 on 2021-11-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='confirmed',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
