# Generated by Django 3.2.7 on 2021-10-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_subject_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
