# Generated by Django 3.2.7 on 2021-10-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_auto_20211013_1406'),
        ('subjects', '0008_auto_20211013_1455'),
    ]

    operations = [
    ]
