# Generated by Django 3.2.7 on 2021-10-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0012_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='confirmed',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
