# Generated by Django 3.2.7 on 2021-10-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0019_alter_subject_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='confirmed',
            field=models.BooleanField(null=True, verbose_name='Schválit předmět'),
        ),
    ]
