# Generated by Django 3.2.7 on 2021-11-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0021_auto_20211103_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='compulsory',
            field=models.CharField(choices=[('povinny', 'Povinný'), ('nepovinny', 'Nepovinný')], default='nepovinny', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('zimní', 'Zimní'), ('letní', 'Letní')], default='zimní', max_length=20),
        ),
    ]
