# Generated by Django 3.2.7 on 2021-10-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='teacher_points',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, verbose_name='teacher_points'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='validity',
            field=models.BooleanField(blank=True, verbose_name='validity'),
        ),
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(upload_to='', verbose_name='picture'),
        ),
    ]
