# Generated by Django 3.2.7 on 2021-11-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_question_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='teacher_points',
        ),
        migrations.AddField(
            model_name='question',
            name='teacher_points',
            field=models.IntegerField(blank=True, default=0, verbose_name='teacher_points'),
        ),
    ]
